import { ProjectInterface } from './Project.interface';

export const ProjectsModel: Array<ProjectInterface> = [
  {
    title: 'Internetics.Group',
    lead_text: 'Internetics.Group landing page with Deno back-end',
    date: '2021-08-01',
    tags: ['Angular', 'TypeScript', 'TailwindCSS', 'RWD', 'Deno'],
    featured_image: '../assets/projects-thumbnails/08-internetics-page.webp',
    project_link: 'https://internetics.piotrkieltyka.website',
    button_icon: 'fab fa-angular fa-lg',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Social Media Dashboard',
    lead_text: 'Social media dashboard with theme switcher / Frontend Mentor',
    date: '2020-05-10',
    tags: ['HTML', 'CSS', 'RWD'],
    featured_image: '../assets/projects-thumbnails/social-desktop-preview.webp',
    project_link:
      'https://piotrkieltyka.github.io/frontendmentor-social-media-dashboard',
    button_icon: 'fab fa-css3-alt',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Fylo Landing Page',
    lead_text:
      'Fylo landing page with dark theme and features grid / Frontend Mentor',
    date: '2020-05-23',
    tags: ['HTML', 'CSS', 'RWD'],
    featured_image: '../assets/projects-thumbnails/fylo-desktop-preview.webp',
    project_link:
      'https://piotrkieltyka.github.io/frontendmentor-fylo-dark-theme-landing-page',
    button_icon: 'fab fa-css3-alt',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Huddle Landing Page',
    lead_text: 'Huddle landing page with curved sections / Frontend Mentor',
    date: '2020-05-20',
    tags: ['HTML', 'CSS', 'RWD'],
    featured_image: '../assets/projects-thumbnails/huddle-desktop-preview.webp',
    project_link:
      'https://piotrkieltyka.github.io/frontendmentor-huddle-landing-page-with-curved-sections',
    button_icon: 'fab fa-css3-alt',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Phonebook App',
    lead_text: 'Ensono - Angular Coding Challenge',
    date: '2019-06-30',
    tags: ['Angular', 'Material', 'TypeScript'],
    featured_image: '../assets/projects-thumbnails/07-ensono-challenge.webp',
    project_link: 'https://github.com/PiotrKieltyka/phonebook',
    button_icon: 'fab fa-angular fa-lg',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Angular Workshop',
    lead_text: 'Angular Core and Reactive Angular with NgRx / Frontend Masters',
    date: '2019-02-03',
    tags: ['Angular', 'Material', 'TypeScript', 'NX', 'RxJS'],
    featured_image: '../assets/projects-thumbnails/05-nrwl-nx-workshop.webp',
    project_link: 'https://github.com/PiotrKieltyka/angular-workshop',
    button_icon: 'fab fa-angular fa-lg',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'userApp Frontend',
    lead_text: 'Project created to develop my programming skills',
    date: '2018-11-28',
    tags: ['Angular', 'Material', 'TypeScript', 'SCSS'],
    featured_image: '../assets/projects-thumbnails/02-userApp-frontend.webp',
    project_link: 'https://github.com/PiotrKieltyka/userApp-nodeServer',
    button_icon: 'fab fa-angular fa-lg',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'userApp Node Server',
    lead_text:
      'API written in TypeScript using Node, Express and connected to MongoDB via Mongoose',
    date: '2018-11-29',
    tags: ['TypeScript', 'Express', 'NodeJS', 'MongoDB', 'Rest API'],
    featured_image: '../assets/projects-thumbnails/01_userApp-nodeServer.webp',
    project_link: 'https://github.com/PiotrKieltyka/userApp',
    button_icon: 'fab fa-node-js fa-lg',
    button_text: 'Visit project',
    categories: 'development',
  },
  {
    title: 'Monitoring App',
    lead_text:
      'Project created for an android phones and tablets to monitoring production and packaging products',
    date: '2019-01-29',
    tags: ['Angular', 'Material', 'RWD', 'TypeScript', 'Android', 'JSON'],
    featured_image:
      '../assets/projects-thumbnails/04-rwd-production-monitor.webp',
    project_link: '',
    button_icon: '',
    button_text: '',
    categories: 'development',
  },
  {
    title: 'SEDATE - Diploma Project',
    lead_text: 'Web App with RWD for Residential Association Management',
    date: '2018-09-01',
    tags: ['Angular', 'RWD', 'Java', 'Rest API', 'PostgreSQL'],
    featured_image: '../assets/projects-thumbnails/06-sedate-frontend.webp',
    project_link: '',
    button_icon: 'fab fa-angular fa-lg',
    button_text: '',
    categories: 'development',
  },
  {
    title: 'Apartamenty na Polanie',
    lead_text: "Project created for my residents' association",
    date: '2015-05-08',
    tags: ['HTML', 'CSS', 'JavaScript'],
    featured_image: '../assets/projects-thumbnails/03-anp1-website.webp',
    project_link: 'https://anp1.pl',
    button_icon: 'fas fa-users fa-lg',
    button_text: 'Visit project',
    categories: '',
  },
];
