name: Website-Deploy

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build using NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install deps
        run: npm i

      - name: Add firebase config file
        env:
          FIREBASE_APIKEY: ${{ secrets.APIKEY }}
          FIREBASE_APPID: ${{ secrets.APPID }}
          FIREBASE_AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          FIREBASE_DATABASEURL: ${{ secrets.DATABASEURL }}
          FIREBASE_PROJECTID: ${{ secrets.PROJECTID }}
          FIREBASE_STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
          FIREBASE_MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
        run: |
          echo 'export const FirebaseConfig = {
            apiKey: `$FIREBASE_APIKEY`,
            authDomain: `$FIREBASE_AUTHDOMAIN`,
            databaseURL: `$FIREBASE_DATABASEURL`,
            projectId: `$FIREBASE_PROJECTID`,
            storageBucket: `$FIREBASE_STORAGEBUCKET`,
            messagingSenderId: `$FIREBASE_MESSAGINGSENDERID`
          };' > src/environments/firebase.config.ts

      - name: Build project
        run: npm run build:prod

      - name: Deploy on server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/website-with-tailwindcss/
          server-dir: ./www/website-with-tailwindcss/
